# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Building application
      run: npm run build --if-present  # Added 'run' key here

    - name: Testing application
      run: npm test  # Added 'run' key here
    
    - name: Post Comment on PR
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
            const comment = `
               🔧 **Test Issues Detected**
              Please, ensure that your code passing all tests. Use the next commend:

              \`\`\`bash
              npm run test
              \`\`\`
              `;

              github.rest.issues.createComment({
              issue_number: context.payload.pull_request?.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
      continue-on-error: false
